import { useEffect, useState } from "react";
import DashboardLayout from "../components/DashboardLayout";
import { Alert, LoadingState } from "../components/Ui";
import api from "../api/axios";
import { getErrorMessage } from "../utils/errors";
function AdminDashboard() {
  const [stats, setStats] = useState(null); const [users, setUsers] = useState([]); const [internships, setInternships] = useState([]); const [error, setError] = useState("");
  const load = async () => { try { const [s, u, i] = await Promise.all([api.get("/admin/stats"), api.get("/admin/users"), api.get("/internships")]); setStats(s.data); setUsers(u.data); setInternships(i.data); } catch (err) { setError(getErrorMessage(err, "Unable to load administration data.")); } };
  useEffect(() => { load(); }, []);
  const toggle = async (user) => { try { await api.put(`/admin/users/${user.id}/active`, { active: !user.active }); load(); } catch (err) { setError(getErrorMessage(err, "Unable to update user.")); } };
  const removeInternship = async (id) => { if (!window.confirm("Remove this internship from UniConnect?")) return; try { await api.delete(`/admin/internships/${id}`); load(); } catch (err) { setError(getErrorMessage(err, "Unable to remove internship.")); } };
  return <DashboardLayout role="ADMIN" title="Platform Overview">{error && <Alert>{error}</Alert>}{!stats ? <LoadingState /> : <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[["Users", stats.users], ["Students", stats.students], ["Companies", stats.companies], ["Internships", stats.internships], ["Applications", stats.applications]].map(([label, value]) => <Stat key={label} label={label} value={value} />)}</div>
    <section className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><Header title="User management" text="Review accounts and control platform access." /><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-6 py-4">User</th><th className="px-6 py-4">Role</th><th className="px-6 py-4">Joined</th><th className="px-6 py-4">Status</th><th className="px-6 py-4 text-right">Action</th></tr></thead><tbody className="divide-y divide-slate-200">{users.map((user) => <tr key={user.id}><td className="px-6 py-4"><p className="font-bold">{user.fullName}</p><p className="text-sm text-slate-500">{user.email}</p></td><td className="px-6 py-4 font-bold text-indigo-600">{user.role}</td><td className="px-6 py-4 text-sm text-slate-500">{new Date(user.createdAt).toLocaleDateString()}</td><td className="px-6 py-4"><span className={`rounded-full px-3 py-1 text-xs font-black ${user.active ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{user.active ? "ACTIVE" : "DISABLED"}</span></td><td className="px-6 py-4 text-right">{user.role !== "ADMIN" && <button onClick={() => toggle(user)} className="btn-secondary">{user.active ? "Disable" : "Restore"}</button>}</td></tr>)}</tbody></table></div></section>
    <section className="mt-7 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><Header title="Internship moderation" text="Review and remove inappropriate or outdated opportunities." /><div className="divide-y divide-slate-200">{internships.map((item) => <div key={item.id} className="flex flex-col justify-between gap-4 p-6 sm:flex-row sm:items-center"><div><p className="font-black">{item.title}</p><p className="mt-1 text-sm text-slate-500">{item.companyName} · {item.location || "No location"}</p></div><button onClick={() => removeInternship(item.id)} className="rounded-xl bg-red-50 px-4 py-2.5 text-sm font-black text-red-700">Remove</button></div>)}</div></section>
  </>}</DashboardLayout>;
}
function Stat({ label, value }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-3xl font-black text-indigo-600">{value}</p></div>; }
function Header({ title, text }) { return <div className="border-b border-slate-200 p-6"><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-sm text-slate-500">{text}</p></div>; }
export default AdminDashboard;
