import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import DashboardLayout from "../components/DashboardLayout";
import { Alert } from "../components/Ui";
import api from "../api/axios";
import { getErrorMessage } from "../utils/errors";
function AccountSettings() {
  const role = localStorage.getItem("role") || "STUDENT"; const navigate = useNavigate();
  const [account, setAccount] = useState({ fullName: "", email: "" }); const [password, setPassword] = useState({ currentPassword: "", newPassword: "" }); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { api.get("/account").then(({ data }) => setAccount(data)); }, []);
  const save = async (event) => { event.preventDefault(); setError(""); try { const emailChanged = account.email !== localStorage.getItem("email"); const { data } = await api.put("/account", { fullName: account.fullName, email: account.email }); localStorage.setItem("fullName", data.fullName); if (emailChanged) { ["token", "role", "email", "userId", "fullName"].forEach((key) => localStorage.removeItem(key)); navigate("/", { state: { message: "Email updated. Please sign in again." } }); } else setMessage("Account details updated."); } catch (err) { setError(getErrorMessage(err, "Unable to update account.")); } };
  const changePassword = async (event) => { event.preventDefault(); setError(""); try { const { data } = await api.put("/account/password", password); setMessage(data.message); setPassword({ currentPassword: "", newPassword: "" }); } catch (err) { setError(getErrorMessage(err, "Unable to change password.")); } };
  const deactivate = async () => { if (!window.confirm("Deactivate your account? You will no longer be able to sign in.")) return; await api.delete("/account"); localStorage.clear(); navigate("/"); };
  return <DashboardLayout role={role} title="Account Settings">{message && <Alert type="success">{message}</Alert>}{error && <Alert>{error}</Alert>}<div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-black">Account details</h2><p className="mt-2 text-sm text-slate-500">Update the name and email used across UniConnect.</p><form onSubmit={save} className="mt-6 space-y-5"><Field label="Full name" value={account.fullName || ""} onChange={(value) => setAccount({ ...account, fullName: value })} /><Field label="Email address" type="email" value={account.email || ""} onChange={(value) => setAccount({ ...account, email: value })} /><button className="btn-primary w-full sm:w-auto">Save details</button></form></section><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-xl font-black">Change password</h2><p className="mt-2 text-sm text-slate-500">Choose a secure password containing at least eight characters.</p><form onSubmit={changePassword} className="mt-6 space-y-5"><Field label="Current password" type="password" value={password.currentPassword} onChange={(value) => setPassword({ ...password, currentPassword: value })} /><Field label="New password" type="password" value={password.newPassword} onChange={(value) => setPassword({ ...password, newPassword: value })} /><button className="btn-primary w-full sm:w-auto">Update password</button></form></section></div>{role !== "ADMIN" && <section className="mt-6 rounded-3xl border border-red-200 bg-red-50 p-5 sm:p-7"><h2 className="text-xl font-black text-red-700">Deactivate account</h2><p className="mt-2 text-sm text-red-600">This prevents future sign-ins. Contact an administrator if you need the account restored.</p><button onClick={deactivate} className="mt-5 min-h-11 w-full rounded-xl bg-red-600 px-5 py-3 text-sm font-black text-white sm:w-auto">Deactivate my account</button></section>}</DashboardLayout>;
}
function Field({ label, type = "text", value, onChange }) { return <label className="block text-sm font-bold text-slate-700">{label}<input required type={type} value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-3.5" /></label>; }
export default AccountSettings;
