import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import DashboardLayout from "../components/DashboardLayout";
import { Alert, LoadingState } from "../components/Ui";
import api from "../api/axios";
import { getErrorMessage } from "../utils/errors";
function CandidateDetails() {
  const { id } = useParams(); const navigate = useNavigate(); const [candidate, setCandidate] = useState(null); const [error, setError] = useState("");
  useEffect(() => { api.get(`/applications/${id}/candidate`).then(({ data }) => setCandidate(data)).catch((err) => setError(getErrorMessage(err, "Unable to load candidate."))); }, [id]);
  const download = async () => { const response = await api.get(`/applications/${id}/candidate/cv`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `${candidate.fullName}-CV.pdf`; link.click(); URL.revokeObjectURL(url); };
  return <DashboardLayout role="COMPANY"><button onClick={() => navigate("/company/applications")} className="btn-secondary mb-6 w-full sm:w-auto">← Back to candidates</button>{error && <Alert>{error}</Alert>}{!candidate && !error && <LoadingState />}{candidate && <div className="grid gap-6 xl:grid-cols-[1fr_300px]"><section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="h-24 bg-gradient-to-r from-indigo-600 to-cyan-500 sm:h-28" /><div className="p-5 sm:p-7"><div className="-mt-14 grid h-20 w-20 place-items-center rounded-2xl border-4 border-white bg-[#111936] text-2xl font-black text-white sm:-mt-16">{candidate.fullName[0]}</div><h1 className="mt-4 break-words text-2xl font-black sm:text-3xl">{candidate.fullName}</h1><p className="break-all text-sm text-indigo-600 sm:text-base">{candidate.email}</p><div className="mt-7 grid gap-4 sm:grid-cols-3"><Info label="University" value={candidate.university} /><Info label="Degree" value={candidate.degreeProgram} /><Info label="Graduation" value={candidate.graduationYear} /></div><h2 className="mt-8 text-lg font-black">About</h2><p className="mt-2 break-words leading-7 text-slate-500">{candidate.bio || "No bio provided."}</p><h2 className="mt-8 text-lg font-black">Skills</h2><div className="mt-3 flex flex-wrap gap-2">{candidate.skills.map((skill) => <span key={skill} className="max-w-full break-words rounded-full bg-indigo-50 px-3 py-1.5 text-sm font-bold text-indigo-700">{skill}</span>)}</div><h2 className="mt-8 text-lg font-black">Education</h2><div className="mt-3 space-y-3">{candidate.education.map((item) => <div key={item.id} className="rounded-2xl bg-slate-50 p-4"><p className="break-words font-black">{item.degree || "Education"}</p><p className="break-words text-sm text-slate-500">{item.institution} · {item.fieldOfStudy}</p></div>)}</div></div></section><aside className="h-fit rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-black">Candidate resources</h2><p className="mt-2 text-sm leading-6 text-slate-500">Review the candidate’s submitted CV before updating their status.</p>{candidate.cvAvailable ? <button onClick={download} className="btn-primary mt-5 w-full">Download CV</button> : <p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-700">No CV uploaded.</p>}<a href={`mailto:${candidate.email}`} className="btn-secondary mt-3 w-full">Contact candidate</a></aside></div>}</DashboardLayout>;
}
function Info({ label, value }) { return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 font-bold">{value || "Not provided"}</p></div>; }
export default CandidateDetails;
