import { useEffect, useState } from "react";
import DashboardLayout from "../components/DashboardLayout";
import { Alert } from "../components/Ui";
import api from "../api/axios";
import { getErrorMessage } from "../utils/errors";
function CvManager() {
  const [info, setInfo] = useState({ available: false, fileName: "" }); const [file, setFile] = useState(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = () => api.get("/students/cv/info").then(({ data }) => setInfo(data)).catch((err) => setError(getErrorMessage(err, "Create your profile before uploading a CV.")));
  useEffect(() => { load(); }, []);
  const upload = async () => { if (!file) return setError("Choose a PDF file first."); setBusy(true); setError(""); const form = new FormData(); form.append("file", file); try { const { data } = await api.post("/students/cv", form); setMessage(data.message); setFile(null); load(); } catch (err) { setError(getErrorMessage(err, "Unable to upload CV.")); } finally { setBusy(false); } };
  const download = async () => { const response = await api.get("/students/cv", { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = info.fileName || "cv.pdf"; link.click(); URL.revokeObjectURL(url); };
  const remove = async () => { if (!window.confirm("Remove your current CV?")) return; await api.delete("/students/cv"); setMessage("CV removed."); load(); };
  return <DashboardLayout role="STUDENT" title="My CV">{message && <Alert type="success">{message}</Alert>}{error && <Alert>{error}</Alert>}<div className="grid gap-6 xl:grid-cols-[1fr_320px]"><section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-7"><div className="rounded-3xl border-2 border-dashed border-indigo-200 bg-indigo-50/50 p-5 text-center sm:p-10"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-white text-3xl shadow-sm">PDF</div><h2 className="mt-5 text-xl font-black">Upload your professional CV</h2><p className="mt-2 text-sm text-slate-500">PDF format only, maximum file size 5 MB.</p><input type="file" accept="application/pdf" onChange={(e) => setFile(e.target.files?.[0] || null)} className="mt-6 block w-full max-w-full rounded-xl border border-slate-300 bg-white px-2 py-3 text-sm sm:mx-auto sm:max-w-md sm:px-4" />{file && <p className="mt-3 break-all text-sm font-bold text-indigo-600">Selected: {file.name}</p>}<button onClick={upload} disabled={busy} className="btn-primary mt-5 w-full sm:w-auto">{busy ? "Uploading..." : "Upload CV"}</button></div></section><aside className="h-fit rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><p className="text-xs font-black uppercase tracking-wider text-slate-400">Current CV</p>{info.available ? <><div className="mt-4 rounded-2xl bg-emerald-50 p-4"><p className="font-black text-emerald-700">Ready for applications</p><p className="mt-1 truncate text-sm text-emerald-700">{info.fileName}</p></div><button onClick={download} className="btn-secondary mt-4 w-full">Download</button><button onClick={remove} className="mt-3 min-h-11 w-full rounded-xl bg-red-50 px-4 py-3 text-sm font-black text-red-700">Remove CV</button></> : <p className="mt-4 text-sm leading-6 text-slate-500">No CV uploaded yet. Companies can download it after you apply.</p>}</aside></div></DashboardLayout>;
}
export default CvManager;
